apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkinsci/blueocean:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: webinterface
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  labels:
    service: jenkins
spec:
  type: NodePort
  ports:
  - port: 8080
    name: webinterface
  selector:
    app: jenkins